### ISSUE TITLE
Problem with latest Ensembl releases

### ISSUE THREAD

**Issue by pnrobinson** [charite/jannovar#399] opened 2018-03-07 11:57 UTC
Issue by @damiansm on Exomiser tracker

https://github.com/exomiser/Exomiser/issues/253

(i) Jannovar fails to generate a .ser file with the latest Ensembl releases as the cdna file contains versioned Ensembl IDs and the other files don't
(ii) Jannovar uses the latest version of the HGNC file download to assign other IDs including the critical entrezGene IDs to each ENSG based entry in the .ser file. The ENSG ID used for a gene can vary between latest HGNC and the version of Ensembl downloaded leading to no entrezId when running Exomiser and no phenotype matching at ll

The temp solution used in the 1802_variant db builds was:
java -Xms4g -Xmx8g -jar jannovar-cli-0.24.jar download -s default_sources.ini -d hg19/ensembl
perl convert_hgnc_to_b37_ensembl_gene_ids.pl
java -Xms4g -Xmx8g -jar jannovar-cli-0.24.jar download -s default_sources.ini -d hg19/ensembl
java -Xms4g -Xmx8g -jar jannovar-cli-0.24.jar download -s default_sources.ini -d hg38/ensembl
perl convert_hgnc_to_b38_ensembl_gene_ids.pl
java -Xms4g -Xmx8g -jar jannovar-cli-0.24.jar download -s default_sources.ini -d hg38/ensembl

where the sources in default_sources.ini where changed to:
```
[hg19/ensembl]
....
gtf=ftp://ftp.ensembl.org/pub/grch37/current/gtf/homo_sapiens/Homo_sapiens.GRCh37.87.gtf.gz
cdna=ftp://ftp.ensembl.org/pub/grch37/current/fasta/homo_sapiens/cdna/Homo_sapiens.GRCh37.cdna.all.fa.gz

[hg38/ensembl]
....
gtf=ftp://ftp.ensembl.org/pub/release-91/gtf/homo_sapiens/Homo_sapiens.GRCh38.91.gtf.gz
cdna=ftp://ftp.ensembl.org/pub/release-91/fasta/homo_sapiens/cdna/Homo_sapiens.GRCh38.cdna.all.fa.gz
```
and logic in perl script is
```
use strict;
use warnings;

system("gunzip Homo_sapiens.GRCh37.cdna.all.fa.gz");
open(IN,"Homo_sapiens.GRCh37.cdna.all.fa");
open(OUT,">Homo_sapiens.GRCh37.cdna.all.fa_fixed");

while (my $line = <IN>){
    $line =~ s/\.\d//g;
    print OUT $line;
}
close IN;
close OUT;
system("mv Homo_sapiens.GRCh37.cdna.all.fa_fixed Homo_sapiens.GRCh37.cdna.all.fa");
system("gzip Homo_sapiens.GRCh37.cdna.all.fa");

system("gunzip Homo_sapiens.GRCh37.87.gtf.gz");
my %b37_symbol_to_id;
open(IN,"Homo_sapiens.GRCh37.87.gtf");
while (my $line = <IN>){
    chop $line;
    my @line = split(/\t/,$line);
    next if $line[2] ne 'gene';
    next if $line[0] =~ /PATCH/;
    my $info = $line[8];
    
    $info =~ s/\"//g;
    $info =~ s/\;//g;
    my @info = split(/ /,$info);
    my $gene_id = $info[1];
    my $gene_symbol = $info[5];
    $b37_symbol_to_id{$gene_symbol}{$gene_id} = 1;
    #print "BEFORE $gene_symbol\t$gene_id\n";
}
close IN;
system("gzip Homo_sapiens.GRCh37.87.gtf");

open(IN,"hgnc_complete_set.txt");
open(OUT,">hgnc_complete_set_fixed.txt");
while (my $line= <IN>){
    #chop $line;
    my @line = split(/\t/,$line);
    my $gene_symbol = $line[1];
    my $gene_id = $line[19];
    if ($b37_symbol_to_id{$gene_symbol} && !$b37_symbol_to_id{$gene_symbol}{$gene_id}){# && $gene_id ne $b37_symbol_to_id{$gene_symbol}){
        foreach my $new_id (keys %{$b37_symbol_to_id{$gene_symbol}}){
            print "$gene_symbol\t$gene_id\t$new_id\n";#.$b37_symbol_to_id{$gene_symbol}{$new_id}."\n";
            $line[19] = $new_id;#$b37_symbol_to_id{$gene_symbol}{$new_id};
        }
    }
    print OUT join("\t",@line);
}
close IN;
close OUT;
system("mv hgnc_complete_set_fixed.txt hgnc_complete_set.txt");
```

**Comment by visze** [comment] 2018-04-13 13:45
I think this is related to #388

**Comment by holtgrewe** [comment] 2019-02-07 15:52
@julesjacobsen Can you boil this down into a simple example "this is what Jannovar does and this is what it should do"?

**Comment by holtgrewe** [comment] 2019-02-07 16:21
OK, I'm getting (1) now. Working on a fix...

**Comment by holtgrewe** [comment] 2019-02-07 16:53
Fixed (1) in 1a2bb217.

**Comment by damiansm** [comment] 2019-02-07 17:14
Thanks Manuel.

Do you understand the other one: (ii) Jannovar uses the latest version of
the HGNC file download to assign other IDs including the critical
entrezGene IDs to each ENSG based entry in the .ser file. The ENSG ID used
for a gene can vary between latest HGNC and the version of Ensembl
downloaded leading to no entrezId when running Exomiser and no phenotype
matching at ll

Essentially for a gene the ENSG can vary between the HGNC and Ensembl files
downloaded by Jannovar. This leads to no entrezId in the .ser file and no
Exomiser result :-(

My perl script had a hacky fix for the HGNC file to put the ENSG ID back to
what it is in the Ensembl file based on gene symbol matching.

**Comment by holtgrewe** [comment] 2019-02-07 17:33
Funny thing, I get it now e.g., `WHAMMP3` has `ENSG00000276141` in GRCh38 and `ENSG00000187667`  in GRCh37 of ENSEMBL release 95!

I'm a bit reluctant to use gene symbols for matching genes by symbol. I'd prefer to use [ecaballus_gene_ensembl__gene__main.txt.gz](ftp://ftp.ensembl.org/pub/grch37/release-95/mysql/ensembl_mart_95/ecaballus_gene_ensembl__gene__main.txt.gz)... I guess that's cool with you as well as it's what's displayed in the Ensembl browser.

*sigh* and when you thought that two things were stable: Entrez and ENSG IDs...

**Comment by damiansm** [comment] 2019-02-07 20:03
You want to use horse genes! ;-)

Make sure you use the hsapiens_gene_ensembl__gene__main.txt.gz  instead!

Are you going to use this instead of the hgnc file then?

**Comment by holtgrewe** [comment] 2019-02-07 21:08
Haha, I already corrected it but the email sent out still said horse ;) Actually, I'd prefer aardvark ;)

What I plan to do is to use the ENSEMBL-provided ENGS-to-HGNC and then use the most current HGNC for mapping to Entrez etc.. This is based on the assumption that at least HGNC have stable IDs.

**Comment by holtgrewe** [comment] 2019-02-11 12:35
@damiansm @julesjacobsen Please confirm that #431 fixes the issue (`develop` should already work for you now).

**Comment by damiansm** [comment] 2019-02-14 13:59
Hi @holtgrewe I did a new .ser build and tested on a bunch of cases I know and all looks pretty good except for one example where we ended up with no entrezGeneID in the Exomiser run and hence no phenotype match. 

I was trying to work out how to pull out the entrezGene annotation from the commandline but failed. Maybe is just an API thing?

Anyhow the example is below. Previously I got a nice annotation to entrezGene 9757 and everything worked fine. Any ideas why it may have disappeared?

```
host-138-37-146-201:~ damiansmedley$ java -jar jannovar-cli-0.28-SNAPSHOT.jar annotate-pos -d data/hg19_ensembl_new_build.ser -c 'chr19:36227863C>T' -vv
Options
JannovarAnnotatePosOptions [genomicChanges=[chr19:36227863C>T], toString()=JannovarAnnotationOptions [useThreeLetterAminoAcidCode=false, nt3PrimeShifting=false, showAll=false, databaseFilePath=data/hg19_ensembl_new_build.ser, toString()=JannovarBaseOptions [reportProgress=true, httpProxy=null, httpsProxy=null, ftpProxy=null, verbosity=3]]]
Deserializing transcripts...
INFO Deserializing JannovarData from data/hg19_ensembl_new_build.ser
INFO Deserialization took 18.18 sec.
#change	effect	hgvs_annotation	messages
chr19:36227863C>T	STOP_GAINED	KMT2B:ENST00000222270.7:c.7348C>T:p.(R2450*)
```

**Comment by holtgrewe** [comment] 2019-02-14 14:33
@damiansm good catch.

The ground truth from ENSEMBL is here:

- https://grch37.ensembl.org/Homo_sapiens/Gene/Summary?db=core;g=ENSG00000272333;r=19:36208921-36229779;t=ENST00000222270

There is no mapping to HGNC...

Note the following text on the GRCh37 link.

> Overlapping RefSeq Gene ID 9757 matches and has similar biotype of protein_coding

Now looking at GRCh38 ENSEMBL of this ENSG

- http://www.ensembl.org/Homo_sapiens/Gene/Summary?db=core;g=ENSG00000272333;r=19:35718019-35738878

Yay, identifiers in Bioinformatics, fun without bounds!

I am extremely reluctant to add matching by gene symbols as they are not stable.

However, ENSEMBL contains the link to Entrez here:

- https://grch37.ensembl.org/Homo_sapiens/Gene/Matches?db=core;g=ENSG00000272333;r=19:36208921-36229779;t=ENST00000222270

I'll try to find the file that contains this link.

**Comment by holtgrewe** [comment] 2019-02-14 14:36
OK, it's `hsapiens_gene_ensembl__ox_entrezgene__dm.txt.gz.bz2`. I'll look into this tomorrow.

**Comment by damiansm** [comment] 2019-02-14 14:50
Thanks @holtgrewe . Mapping IDs sucks! Glad you are managing to find a use for the Ensembl BioMart tables I created in a previous life at least :-)

Forgot to say a quick grep on my results seemed to show we have less results coming back with no entrezGene match with your new strategy so definitely better than my previous hack!

**Comment by damiansm** [comment] 2019-02-21 16:27
Hi @holtgrewe . Did you get a chance to check the above. Also is there an ETA for the next release. Just trying to decide how and when to do the Exomiser 12.0.0 release and this is one of our last issues now :-)

**Comment by holtgrewe** [comment] 2019-02-22 16:18
@damiansm I'll look into this next week.

**Comment by holtgrewe** [comment] 2019-02-25 17:01
Hi @damiansm please check #434 whether it works for you (I'll merge once the tests are through). Once this has been merged, I'll make the next Jannovar release.

The mapping order is now:

- if HGNC ENSG mapping exists, use it,
- else if ENSEMBL has mapping from ENSG to HGNC, use it,
- else if ENSEMBL has mapping from ENSG to Entrez, use it.

HTH

**Comment by damiansm** [comment] 2019-02-27 13:04
Hi @holtgrewe Tested and looks perfect now. Many thanks

**Comment by julesjacobsen** [comment] 2019-02-27 15:42
@holtgrewe one last request - can you set the logging level from info to debug for these [two lines](https://github.com/charite/jannovar/blob/368762d1730d543ac304a8d9f1fc0f1aaf952ed4/jannovar-core/src/main/java/de/charite/compbio/jannovar/impl/parse/ensembl/EnsemblParser.java#L117-L124):

```java
LOGGER.info(
		"ENSEMBL Gene {} not known to HGNC, annotating with ENTREZ_ID := {} for additional IDs",
						new Object[]{val.getGeneID(), entrezGeneId});
	val.getAltGeneIDs().put(AltGeneIDType.ENTREZ_ID.toString(), entrezGeneId);
}
LOGGER.info(
		"ENSEMBL Gene {} not known to HGNC, annotating with ENSEMBL_GENE_ID := {} for additional IDs",
	new Object[]{val.getGeneID(), val.getGeneID()});
```

Also when writing to the logger you don't need to create a ```new Object[]```, just add the values you want.

**Comment by holtgrewe** [comment] 2019-02-28 17:13
@julesjacobsen  sure. I'm having trouble rebasing and squashing your branches, maybe you could start your next PR from a clean upstream develop?

@damiansm thanks, will release now.

**Comment by holtgrewe** [comment] 2019-02-28 17:34
OK, released v0.28 through Maven central, might take some hours to work.

**Comment by akmit123** [comment] 2019-12-20 20:22
Hi, I downloaded jannovar-cli-0.34-0 (conda download) in a ubuntu linux in AWS and installed. 
Although it does download for hg38  as .gtf file and other files from both ensembl or refseq but still does not convert them to .ser file!  Thus, I can not run/annotate the vcf file as it is telling that database file is not correct! Although documentation file (November 19, 2019) states that jannovar would create a .ser file during download!

commands:
 java -jar jannovar-cli-0.34.jar  download -d hg38/refseq
 java -jar jannovar-cli-0.34.jar  download -d hg38/ensembl
Could anybody help?
Thanks,
Amit

**Comment by holtgrewe** [comment] 2019-12-21 12:21
Hi, please provide the full output of the download commands.

**Comment by akmit123** [comment] 2019-12-21 15:04
command:
java -jar jannovar-cli-0.34.jar download -d hg38/ensembl
output:
-rw-rw-r-- 1 ubuntu ubuntu     1243 Dec 20 19:10 chr_accessions_GRCh38.p12
-rw-rw-r-- 1 ubuntu ubuntu     5092 Dec 20 19:10 chromInfo.txt.gz
-rw-rw-r-- 1 ubuntu ubuntu 14111559 Dec 20 19:10 hgnc_complete_set.txt
-rw-rw-r-- 1 ubuntu ubuntu 41862461 Dec 20 19:10 Homo_sapiens.GRCh38.91.gtf.gz
-rw-rw-r-- 1 ubuntu ubuntu 65088589 Dec 20 19:08 Homo_sapiens.GRCh38.cdna.all.fa.gz
-rw-rw-r-- 1 ubuntu ubuntu  4841046 Dec 20 19:10 hsapiens_gene_ensembl__gene__main.txt.gz
-rw-rw-r-- 1 ubuntu ubuntu   661564 Dec 20 19:10 hsapiens_gene_ensembl__ox_entrezgene__dm.txt.gz
-rw-rw-r-- 1 ubuntu ubuntu   867360 Dec 20 19:10 hsapiens_gene_ensembl__ox_hgnc__dm.txt.gz

**Comment by holtgrewe** [comment] 2019-12-21 17:51
@akmit123 let me clarify: send me the output to stdout/stderr from the java call.

**Comment by akmit123** [comment] 2019-12-21 18:50
Hi Manual,                     Thanks for your mail.
Here is the java call! One reason could be memory problem that I did not see earlier! I will increase the memory of the computer and download again. If it creates .ser file, I will let you know. Except memory problem, if anything else happening, please let me know.
Wishes,
Amit
ubuntu@ip-172-31-14-22:/opt/programs/wgs/ref$ java -jar /opt/programs/jannovar-cli-0.34-0/jannovar-cli-0.34.jar  download -d hg38/ensemblOptionsJannovarDownloadOptions [downloadDir=data, getDataSourceFiles()=[bundle:///default_sources.ini], isReportProgress()=true, getHttpProxy()=null, getHttpsProxy()=null, getFtpProxy()=null, geneIdentifiers=[], outputFile=]Downloading/parsing for data source "hg38/ensembl"INFO Downloading data...INFO Downloading https://ftp.ensembl.org/pub/release-91/fasta/homo_sapiens/cdna/Homo_sapiens.GRCh38.cdna.all.fa.gz[==================================================]   100%INFO Downloaded file Homo_sapiens.GRCh38.cdna.all.fa.gz looks like a valid gzip'ed fileINFO Downloading https://ftp.ensembl.org/pub/release-91/gtf/homo_sapiens/Homo_sapiens.GRCh38.91.gtf.gz[==================================================]   100%INFO Downloaded file Homo_sapiens.GRCh38.91.gtf.gz looks like a valid gzip'ed fileINFO Downloading http://hgdownload.soe.ucsc.edu/goldenPath/hg38/database/chromInfo.txt.gz[==================================================]   100%INFO Downloaded file chromInfo.txt.gz looks like a valid gzip'ed fileINFO Downloading https://ftp.ncbi.nlm.nih.gov/genomes/H_sapiens/ARCHIVE/ANNOTATION_RELEASE.109/Assembled_chromosomes/chr_accessions_GRCh38.p12[==================================================]   100%INFO Downloading https://ftp.ensembl.org/pub/release-95/mysql/ensembl_mart_95/hsapiens_gene_ensembl__gene__main.txt.gz[==================================================]   100%INFO Downloaded file hsapiens_gene_ensembl__gene__main.txt.gz looks like a valid gzip'ed fileINFO Downloading https://ftp.ensembl.org/pub/release-95/mysql/ensembl_mart_95/hsapiens_gene_ensembl__ox_hgnc__dm.txt.gz[==================================================]   100%INFO Downloaded file hsapiens_gene_ensembl__ox_hgnc__dm.txt.gz looks like a valid gzip'ed fileINFO Downloading https://ftp.ensembl.org/pub/release-95/mysql/ensembl_mart_95/hsapiens_gene_ensembl__ox_entrezgene__dm.txt.gz[==================================================]   100%INFO Downloaded file hsapiens_gene_ensembl__ox_entrezgene__dm.txt.gz looks like a valid gzip'ed fileINFO Downloading http://ftp.ebi.ac.uk/pub/databases/genenames/new/tsv/hgnc_complete_set.txt[==================================================]   100%INFO Building ReferenceDictionary...INFO Parsing transcripts...INFO Loading feature recordsINFO Determined GTF/GFF file version to be GTFWARN Found no Entrez ID identifier for ENSG:WARN Found no Entrez ID identifier for ENSG:WARN Found no Entrez ID identifier for ENSG:INFO Assigning additional HGNC information to transcripts..INFO Adding sequence information from cdna FASTA...Exception in thread "main" java.lang.OutOfMemoryError: Java heap space        at java.util.Arrays.copyOfRange(Arrays.java:3664)        at java.lang.String.<init>(String.java:207)        at java.lang.StringBuilder.toString(StringBuilder.java:407)        at com.google.common.base.Joiner.join(Joiner.java:197)        at com.google.common.base.Joiner.join(Joiner.java:187)        at de.charite.compbio.jannovar.impl.parse.FASTAParser.buildRecord(FASTAParser.java:93)        at de.charite.compbio.jannovar.impl.parse.FASTAParser.next(FASTAParser.java:79)        at de.charite.compbio.jannovar.impl.parse.ensembl.EnsemblParser.loadFASTA(EnsemblParser.java:316)        at de.charite.compbio.jannovar.impl.parse.ensembl.EnsemblParser.run(EnsemblParser.java:132)        at de.charite.compbio.jannovar.datasource.EnsemblJannovarDataFactory.parseTranscripts(EnsemblJannovarDataFactory.java:34)        at de.charite.compbio.jannovar.datasource.JannovarDataFactory.build(JannovarDataFactory.java:106)        at de.charite.compbio.jannovar.cmd.download.DownloadCommand.run(DownloadCommand.java:43)        at de.charite.compbio.jannovar.Jannovar.main(Jannovar.java:67)


    On Saturday, December 21, 2019, 12:51:28 PM EST, Manuel Holtgrewe <notifications@github.com> wrote:  
 
 
@akmit123 let me clarify: send me the output to stdout/stderr from the java call.

**Comment by akmit123** [comment] 2020-01-04 13:13
Thanks Holtgrewe, after increasing memory of the computer, Jannovar is running and giving the output file with annotated variants. However, for some file, but not all, program prematurely terminates and generate truncated output file. Although it seems to me benign because it terminates after generating most of the output file. However you may fix the bug in future.

Output after running commands:

INFO Deserializing JannovarData from /home/ec2-user/miniconda3/share/jannovar-cli-0.34-0/data/hg38_refseq.ser
INFO Deserialization took 24.28 sec.
Location        processed.sites runtime.per.1M.sites    completed       total.runtime   remaining
Annotating VCF...
Will read full input file
..........................................................................
.......................................................................
Here is the error after running from ch1 to ch 15

 chr15:79,608,469        33015865        250.0   29.7%   7.7 h   5.4 h
chr15:88,018,291        33323232        249.5   30.0%   7.7 h   5.4 h
chr15:95,089,713        33621181        249.1   30.2%   7.7 h   5.4 h
Exception in thread "main" java.lang.Error: Bug: problem with projection!
        at de.charite.compbio.jannovar.annotation.VCFAnnotationData.setAnnoLoc(VCFAnnotationData.java:117)
        at de.charite.compbio.jannovar.annotation.Annotation.toVCFAnnoString(Annotation.java:287)
        at de.charite.compbio.jannovar.htsjdk.VariantContextAnnotator.applyAnnotations(VariantContextAnnotator.java:400)
        at de.charite.compbio.jannovar.htsjdk.VariantContextAnnotator.dispatchAnnotateVariantContext(VariantContextAnnotator.java:337)
        at de.charite.compbio.jannovar.htsjdk.VariantContextAnnotator.annotateVariantContext(VariantContextAnnotator.java:296)
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
        at java.util.Iterator.forEachRemaining(Iterator.java:116)
        at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.util.stream.ReferencePipeline.forEachOrdered(ReferencePipeline.java:423)
        at de.charite.compbio.jannovar.cmd.annotate_vcf.AnnotateVCFCommand.run(AnnotateVCFCommand.java:411)
        at de.charite.compbio.jannovar.Jannovar.main(Jannovar.java:67)
Caused by: de.charite.compbio.jannovar.reference.ProjectionException: Invalid transcript sequence position 2994
        at de.charite.compbio.jannovar.reference.TranscriptProjectionDecorator.transcriptToGenomePos(TranscriptProjectionDecorator.java:170)
        at de.charite.compbio.jannovar.annotation.VCFAnnotationData.setAnnoLoc(VCFAnnotationData.java:113)
        ... 15 more

**Comment by holtgrewe** [comment] 2021-06-09 09:48
Closing in favour of #524.

**Closed by holtgrewe** 2021-06-09 09:48 UTC
Labels: bug
