### ISSUE TITLE
HGVS to VCF conversion reference sequence error

### ISSUE THREAD

**Issue by GSalma** [charite/jannovar#397] opened 2018-03-05 10:11 UTC
Correct HGVS codes giving an error because of wrong reference sequence retrieved: 

Example : NM_020732.3:c.3919C>T

Error : WARN Invalid reference nucleotides in 6:g.157517355C>T, should be T, auto-correcting.
Exception in thread "main" java.lang.IllegalArgumentException: Duplicate allele added to VariantContext: T

**Comment by visze** [comment] 2018-03-13 16:30
Hey

I tried it with the actual development version (v25-SNAPSHOT). I do not get the error! And the result in the VCF seems to be fine.

```text
CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO
6       157517355       .       C       T       .       .       .
```


Then I tried it with the actual version (v24) and I can reproduce your error. 

I think this is because happens because of a bug in the actual version retrieving the wrong contig of the reference sequence. This is fixed in the actual development (see PR #395) and will be present in the newest release. 

If you want to use the `hgvs-to-vcf` please use the actual development version. it will take some time for the next release.

**Closed by visze** 2018-03-13 16:30 UTC
